apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dashboard.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "dashboard.labels" . | nindent 4 }}
data:
  CLICKHOUSE_HUD_USER_URL: {{ .Values.clickhouse.url | quote }}
  CLICKHOUSE_HUD_USER_USERNAME: {{ .Values.clickhouse.username | quote }}
  NEXTAUTH_URL: {{ .Values.nextauthUrl | quote }}
  NEXTAUTH_SECRET: {{ .Values.secrets.authSecret | quote }}
  NODE_ENV: "production"
  NO_COLOR: "1"
  FORCE_COLOR: "0"
  PORT: {{ .Values.pod.port | quote }}
