apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dashboard.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "dashboard.labels" . | nindent 4 }}
type: Opaque
stringData:
  CLICKHOUSE_HUD_USER_PASSWORD: {{ .Values.secrets.clickhousePassword | quote }}
  AUTH_SECRET: {{ .Values.secrets.authSecret | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  INTERNAL_API_TOKEN: {{ .Values.secrets.internalApiToken | quote }}
  GITHUB_CLIENT_ID: {{ .Values.secrets.githubClientId | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.secrets.githubClientSecret | quote }}
